<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Acessar Sistema Estoque</title>

    <link rel="canonical" href="<?=HOME;?>/auth/login">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="<?=HOME;?>/assets/css/login.css" rel="stylesheet">
  </head>

  <body class="text-center">
    
    <main class="form-signin w-100 m-auto">
      <?php if($mensagem = recuperarMesagemFlash('error')): ?>

        <div class="alert alert-danger"><?=$mensagem;?></div>

      <?php endif;?>

      <form action="<?=HOME;?>?pagina=/auth/post-login" method="post">
          <h1 class="h3 mb-3 fw-normal">Acessar Sistema Estoque</h1>

          <div class="form-floating">
          <input type="email" name="email" class="form-control" id="floatingInput" placeholder="nome@email.com">
          <label for="floatingInput">E-mail</label>
          </div>
          <div class="form-floating">
          <input type="password" name="senha" class="form-control" id="floatingPassword" placeholder="Senha">
          <label for="floatingPassword">Senha</label>
          </div>

          <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
          <p class="mt-5 mb-3 text-muted">&copy; <?=date('Y');?></p>
      </form>
    </main>
  </body>
</html>
