<?php require TEMPLATES . '/includes/cabecalho.phtml'; ?>

<h1>Editar Produto</h1>

<form 
    action="<?php echo HOME;?>?pagina=/produtos/atualizar&produto=<?=$produto['id'];?>" 
    method="post" enctype="multipart/form-data" 
    >

    <div class="form-group mb-3">

        <label>Nome Produto</label>
        <input class="form-control"
            type="text" name="nome" 
            placeholder="Nome do Produto..."
            value="<?=$produto['nome'];?>">

    </div>  
    
    <div class="form-group mb-3">

        <label>Descrição Produto</label>
        <input class="form-control"
            type="text" name="descricao" 
            placeholder="Descrição do Produto..."
            value="<?=$produto['descricao'];?>">

    </div>

    <div class="form-group mb-3">

        <label>Sobre o Produto</label>
        <textarea class="form-control"
            name="sobre" 
            placeholder="Sobre o Produto..."><?=$produto['sobre'];?></textarea>

    </div>

    <div class="form-group mb-3">

        <label>Valor do Produto</label>
        <input class="form-control"
            type="text" name="preco" 
            placeholder="Valor do Produto..."
            value="<?=number_format($produto['preco'], 2, ',', '.');?>">

    </div>

    <div class="form-group mb-3">

        <label>Status</label>
        <select name="status" class="form-control">

            <option value="1" 
                
                <?=$produto['status'] == 1 ? 'selected' : '';?>

            >Ativo</option>

            <option value="0"  
                
                <?=!$produto['status'] ? 'selected' : '';?>

            >Inativo</option>

        </select>

    </div>

    <div class="form-group mb-3">

        <div class="row">
            <div class="col-4">
                <?php if($produto['foto']): ?>
                    <img src="<?=HOME . '/uploads/imagens/';?><?=$produto['foto'] ?>" alt="" class="img-fluid">
                <?php endif;?>
            </div>
            
            <div class="col-8">
                <label>Foto(s) Produto</label>

                <input class="form-control" type="file" name="foto" multiple>
            </div>
        </div>

    </div>
    
    <button class="btn btn-lg btn-success">Atualizar Produto</button>
</form>

<?php require TEMPLATES . '/includes/rodape.phtml'; ?>
