<?php require TEMPLATES . '/includes/cabecalho.phtml'; ?>


<div class="d-flex justify-content-between align-items-center mb-5">
    <h2>Produtos</h2>
    
    <a href="<?=HOME . '?pagina=/produtos/criar'?>" class="btn btn-success">Criar Produto</a>
</div>

<div>
    
    <table class="table">
        <thead>
            <tr>
                <th>Foto</th>
                <th>#</th>
                <th>Produto</th>
                <th>Estoque</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($produtos as $produto) : ?>
                <tr>
                    <td width="10%">
                        <?php if($produto['foto']): ?>
                            <img src="<?=HOME . '/uploads/imagens/';?><?=$produto['foto'] ?>" alt="" class="img-fluid">
                        <?php else: ?>
                            <strong>Sem Foto</strong>
                        <?php endif;?>
                    </td>
                    <td style="width: 5%; text-align: center;"><?=$produto['id'] ?></td>
                    <td style="width: 55%;"><?=$produto['nome'] ?></td>

                    <td style="width: 10%;"><?=$produto['quantidade']??=0 ?></td>

                    <td>
                        <a  class="btn btn-sm btn-primary"
                            href="<?=HOME; ?>/?pagina=/produtos/editar&produto=<?=$produto['id'] ?>">
                            Editar
                        </a> 

                        <a class="btn btn-sm btn-danger"
                            href="<?=HOME; ?>/?pagina=/produtos/remover&produto=<?=$produto['id'] ?>">
                            Remover
                        </a>

                        <button type="button" id="estoque" class="btn btn-sm btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal" data-produto="<?=$produto['id'];?>">
                        Estoque
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
   const URL_BASE = 'http://localhost:3030/';

   document.addEventListener('DOMContentLoaded', event => {

    let btnEstoque = document.querySelectorAll('button#estoque')

    for(let elemento of btnEstoque) {
        //To-DO: Ao clicar no elemento button com o id estoque, eu quero fazer algo
        elemento.addEventListener('click', event => {
            let produtoId = event.target.dataset.produto

            document.querySelector('input#produto').value = produtoId
        })
    }

    let formEstoque = document.querySelector('form#controleEstoqueForm')

    document.querySelector('button#adicionarEstoque').addEventListener('click', event => {
        let formData = new FormData(formEstoque)
    
        //AJAX - Asycronous Javascript and XML|json
        ajax('/estoque/adicionar', formData)
    })

    document.querySelector('button#retirarEstoque').addEventListener('click', event => {
        let formData = new FormData(formEstoque)
    
        //AJAX - Asycronous Javascript and XML|json
        ajax('/estoque/retirar', formData)
    })

    function ajax(endpoint, formData) {

        fetch(`${URL_BASE}?pagina=${endpoint}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'   
            },
            body: `quantidade=${formData.get('quantidade')}&produto=${formData.get('produto')}`
        })
        .then(async resposta => {
            let respostaParse = await resposta.json()

            if(!resposta.ok) throw new Error(respostaParse.mensagem)

            return respostaParse
        })
        .then(resposta => {
            document.querySelector('div#mensagem').innerHTML = `<div class="alert alert-success">
                                                                ${resposta.mensagem}</div>`
            
            formEstoque.reset()

            setTimeout(() => { 
                document.location.reload()
            }, 3000)
        })
        .catch(error => document.querySelector('div#mensagem').innerHTML = `<div class="alert alert-danger">
                                                                ${error}</div>`)
    }

   })

</script>

<?php require TEMPLATES . '/includes/modal-estoque.phtml';?>
<?php require TEMPLATES . '/includes/rodape.phtml'; ?>